### ISSUE TITLE
Nuterra 0.4.2.1 Issue

### ISSUE THREAD

**Issue by lexex192** [maritaria/terratech-mod#83]
Direct Log:
1. Select TerraTech install directory
2. Click "Install" button
3. Enjoy Nuterra (optional)

Selected directory: The selected directory is valid, install can be started

Modding Assembly-CSharp.dll
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`
Raw assembly hash: `fExVArgiHAilnynHYYiUuA==`

   at Nuterra.Build.FindCleanAssembly.Perform(ModificationInfo info)
   at Nuterra.Build.ModificationStep.PerformInternal(ModificationInfo info)
   at Nuterra.Build.ModificationStep.PerformInternal(ModificationInfo info)
   at Nuterra.Build.InstallProgram.PerformInstall(ModificationInfo info)
   at Nuterra.Installer.MainForm.InstallerWorkerMethod()

Your local install cannot be used to install Nuterra into, and no compatible backup exists
Install failed

**Comment by gamerCat898** [comment]
Same problem, please come back!
